# Used to keep the Documentation always up to date
# Source https://github.com/marketplace/actions/docfx-action
name: Generate Documentation

on:
  push:
    branches:
      - master

jobs:
  generateDocumentation:
    runs-on: ubuntu-latest
    name: Generate Documentation
    steps:
    - name: Checkout VrVektoren
      uses: actions/checkout@v2

    - name: Checkout Dokumenation
      uses: actions/checkout@v2
      with:
        repository: VrVektoren/VrVektoren.github.io
        path: docs

    - uses: nikeee/docfx-action@master
      name: Build Documentation
      with:
        args: docfx.json
    
    - name: Deploy Documenation
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        REPOSITORY_NAME: VrVektoren/VrVektoren.github.io
        FOLDER: docs
        BRANCH: master
